### ISSUE TITLE
방출자의 방출 당시 순위가 그대로 노출되는 현상

### ISSUE THREAD

**Issue by rika-lee** [siluat/produce48#11]
방출자의 방출 당시 순위가 그대로 노출되는 현상.

예를 들어, 마츠이 쥬리나 방출 당시 순위 13이 그대로 표시되어
현재 13위인 시로마 미루와 중복됨.

**Comment by siluat** [comment]
방출자는 마지막의 순위를 표시,
중도 하차 인원은 마지막 순위라는 것이 애매하다고 생각되어 그냥 표시를 하지 않는 것으로.

@rika-lee 이 정도로 괜찮으시면, 클로즈 디스 이슈.
